//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUpWithLoginMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class user
    {
        public int Id { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage="First Name is Required field")]
        public string firstName { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last Name is Required field")]
        public string lastName { get; set; }

        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender is Required field")]
        public string gender { get; set; }

        [DisplayName("Age")]
        [Required(ErrorMessage = "Age is Required field")]
        public int age { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Email is Required field")]
        public string email { get; set; }

        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is Required field")]
        public string username { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is Required field")]
        [DataType(DataType.Password)]
        public string passsword { get; set; }


        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "Confirm Password is Required field")]
        [DataType(DataType.Password)]
        [Compare("passsword", ErrorMessage ="Password is not same")]
        public string confirm_passsword { get; set; }

    }
}
